[package]
name = "shell-t"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.10"
which = "6.0"
libc = "0.2"
